name: Build
run-name: Build and test of commit "${{ github.event.head_commit.message }}"

on:
  push:
    branches:
      - "*"

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} \
          -DCMAKE_BUILD_TYPE=Release \
          -S ${{ github.workspace }}

    - name: Build
      run: |
        cmake --build ${{ steps.strings.outputs.build-output-dir }}

    - name: Download index files
      run: |
        mkdir indexes
        cd indexes
        wget http://data.astrometry.net/4100/index-4109.fits

    - name: Run example application
      run: |
        ${{ steps.strings.outputs.build-output-dir }}/bin/example example/starfield.jpg indexes
